### ISSUE TITLE
How do I train my own model

### ISSUE THREAD

**Issue by Zumbalamambo** [baileyfriend/Gender-Image-Classifier#1]
How do I use this code to train my own model and test it realtime?

**Comment by baileyfriend** [comment]
Hello! 

To use this to create your own model you would do a few steps:

- Download lots of facial images - I used the LFW dataset:  http://vis-www.cs.umass.edu/lfw/

- run the image_classifier.py script
     - This will write your model to a JSON file and the weights for your model to an h5 file. 

This can be used to classify images by:

- Importing your model and load your weights

- read images you'd like to classify into numpy array

- Call the 'model.predict()' function on your numpy array representation of the image you'd like to classify.

An example of this can be found in the testing.py file.
